{% set version = '1.2-1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-english
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/english_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/english/english_{{ version }}.tar.gz
  sha256: 7b299bf875841e5840f1b9a39da016fccce263bcdfa70ccfb57eff10c8a82d12

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('english')"           # [not win]
    - "\"%R%\" -e \"library('english')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=english
  license: GPL-2
  summary: Allow numbers to be presented in an English language version, one, two, three, ...
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
    - CurtLH

# Package: english
# Type: Package
# Title: Translate Integers into English
# Version: 1.2-1
# Date: 2019-02-20
# Author: John Fox, Bill Venables, Anthony Damico and Anne Pier Salverda
# Maintainer: Bill Venables <Bill.Venables@gmail.com>
# Description: Allow numbers to be presented in an English language version, one, two, three, ...
# Suggests: utils
# License: GPL-2
# LazyLoad: yes
# NeedsCompilation: no
# Encoding: UTF-8
# RoxygenNote: 6.1.1
# Packaged: 2019-02-20 22:09:06 UTC; ven037
# Repository: CRAN
# Date/Publication: 2019-02-26 22:00:06 UTC
