travis:
  secure:
    BINSTAR_TOKEN: A+GPvVjZW1hadajPCxnUQjkvNIeQP3h+60pogXHurUPz0h5lIA2uSaO4SHKoGbE6X1Pe2GB8VMbg7l0Su7Mn040n2v0rLoMUrjJrE3Na5kyYemMFOiAWrJ6+13D67tSZyWQEXP50rm+dXMtM7zD7FcsvEcDwrPTHhGce/9+4ZO4/cfbjj2KETrnPSPcTT970y/EwIPdJhceQzVObNU4FuZ6NL7kZEAQWsrcAYZA7YtaFrdjb+kcezZ02QfDUEUE9qahfQKSP5WZyYgFJSUxqY3bMBafDyER35Lq6jzdtGlom2567K+dKNrfOX2xhk27dgCxaT4iKk455lVTu9OeTbSuc6xG5r5cuycAv70FxupRZZSPvzIu2Z7cyE3n5xN71dket2OB+MlEZdGfLd4HsjOeGiKh1vXOykHl5mgk1HJHUSDgLPlapMxOuzHvY9RDoJknGo3T7QlXuQP+TAWbQZTpr+a/sLOSyrtowW/Z+S2WwXn9xSkfm6B1aBLvtUrawit5IhcWdNDNzVCys18yIDXO3MbUPahwTmzvj6syoK/whg7HGSLhBGs43W3zBzb1YRbJP91DmQrTJneRidAle/PKUCTis+LMNQhF2kv/j2Dh3f7oSqHe6JQfVsWMEvd/p+XUygXKwNNlEq7odX7QV5nJAE20gSnhv1lxHrIaNTNY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
