travis:
  secure:
    BINSTAR_TOKEN: CKtTQ1DgsP7ZPNQWsTa3gqT8qfkwp7bqP9wa0cvatdd/uJvhXaV6Rzx0ISorpdQ6+o+Uw6Y4FUqnQpFIZISQglMo1NJogI3jKWpwNH0EdOpLGZkIP3Icc5H9yWKJ2RwUZOJMNdKVmLaWe8aEXLipka9nTjVM7znu/VT+OeyJroEOxK0QcmYlyg8zhLA+hhpPsuQ0bm8vDvYiESvcrS6bGYz5sb7MzxYaNuz0zjI1HnoRZ1ezNwKfj2mCYiCZWRA8hWeF3BcCIRJpYLLqh5NVDdrqU4oUAOCbyFYo6EJ7noLBnvKYHUzFynFZgFsv8lEuoQ5R/BvKmSph9ymk2Hz3NQ5iBN7Ge/xsmMoFOzczdrKCWfM4t7Lqg/Hegf0baS7i8apkbX2TnRx1Cn0WJbMEwKI7Xe+NGAylPXw67eCyR6NDahdoKFAWQeAVUFHHb9sRo/LBjlL6r4kUvzzcu5d4gvF+mnqLL8F7KJaU0x9DwMQkKKv8nhoSkALucNhu/8jeCc6wk3a/bqHozJA0qTWgwgVdS1GFwrXAfF32OLLoJW0IDm1QH+g+skGcQUZP9v2h8A5KYJydzt2n0am2XJAD/lAcsVE5vqFvLUxLtSzBCQzBMyHLmk/D83q9ItHDLk0ZBarT1lecBEECpqycbfKhAnaHmIVzkETTzlIAwBzzi8Q=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
